export type Yard = "image" | "text" | "ai" | "docs";

export interface Tool {
  name: string;
  slug: string;
  yard: Yard;
  tagline: string;
  /** The paid incumbent this tool replaces. Empty string = show "free forever". */
  incumbent: string;
}

export const YARDS: { id: Yard; label: string }[] = [
  { id: "image", label: "Image & Media" },
  { id: "text", label: "Text & Code" },
  { id: "ai", label: "In-browser AI" },
  { id: "docs", label: "Docs & Utility" },
];

// 42 tools -- order is canonical; card numbers (#NN) are derived from index + 1.
export const TOOLS: Tool[] = [
  {
    name: "Image Converter",
    slug: "convert",
    yard: "image",
    tagline: "HEIC to JPG, WebP & PNG, compress & resize",
    incumbent: "TinyPNG",
  },
  {
    name: "QR Code",
    slug: "qr",
    yard: "image",
    tagline: "QR codes with logo, colours & dot styles",
    incumbent: "qr-generator",
  },
  {
    name: "Image to Text",
    slug: "ocr",
    yard: "image",
    tagline: "Pull text out of any image (OCR)",
    incumbent: "i2OCR",
  },
  {
    name: "OG Image",
    slug: "og",
    yard: "image",
    tagline: "Social share cards, 1200x630",
    incumbent: "Vercel OG",
  },
  {
    name: "EXIF Viewer",
    slug: "exif",
    yard: "image",
    tagline: "See & strip photo metadata + GPS",
    incumbent: "metadata2go",
  },
  {
    name: "Favicon",
    slug: "favicon",
    yard: "image",
    tagline: "Any image into a full favicon set",
    incumbent: "favicon.io",
  },
  {
    name: "Background Remover",
    slug: "bg",
    yard: "image",
    tagline: "Erase backgrounds with on-device AI",
    incumbent: "remove.bg",
  },
  {
    name: "Collage Maker",
    slug: "collage",
    yard: "image",
    tagline: "Grid + freeform photo collages",
    incumbent: "Canva",
  },
  {
    name: "Screenshot Beautifier",
    slug: "screenshot",
    yard: "image",
    tagline: "Frame shots with bg, padding, shadow",
    incumbent: "shots.so",
  },
  {
    name: "Meme Generator",
    slug: "meme",
    yard: "image",
    tagline: "Top/bottom text, no watermark",
    incumbent: "imgflip",
  },
  {
    name: "Image Cropper",
    slug: "crop",
    yard: "image",
    tagline: "Crop, rotate, flip & resize",
    incumbent: "iLoveIMG",
  },
  {
    name: "SVG Optimizer",
    slug: "svg",
    yard: "image",
    tagline: "Shrink SVG files with SVGO",
    incumbent: "SVGOMG",
  },
  {
    name: "GIF Maker",
    slug: "gif",
    yard: "image",
    tagline: "Turn images into animated GIFs",
    incumbent: "EZGIF",
  },
  {
    name: "JSON Formatter",
    slug: "json",
    yard: "text",
    tagline: "Format, validate & minify JSON",
    incumbent: "jsonformatter",
  },
  {
    name: "Text Diff",
    slug: "diff",
    yard: "text",
    tagline: "Compare two texts, every change",
    incumbent: "diffchecker",
  },
  {
    name: "Markdown",
    slug: "markdown",
    yard: "text",
    tagline: "Write Markdown with live preview",
    incumbent: "StackEdit",
  },
  {
    name: "Base64",
    slug: "base64",
    yard: "text",
    tagline: "Encode & decode text and files",
    incumbent: "base64encode",
  },
  {
    name: "Regex Tester",
    slug: "regex",
    yard: "text",
    tagline: "Live matches, groups & explanation",
    incumbent: "regex101",
  },
  {
    name: "CSS Toolkit",
    slug: "css",
    yard: "text",
    tagline: "Shadow, gradient, glass & easing",
    incumbent: "cssgradient",
  },
  {
    name: "CSV / JSON",
    slug: "csv",
    yard: "text",
    tagline: "Convert CSV to JSON and back",
    incumbent: "convertcsv",
  },
  {
    name: "Timestamp",
    slug: "timestamp",
    yard: "text",
    tagline: "Unix epoch to human dates",
    incumbent: "epochconverter",
  },
  {
    name: "UUID",
    slug: "uuid",
    yard: "text",
    tagline: "v4, v7 & nano IDs in bulk",
    incumbent: "uuidgenerator",
  },
  {
    name: "Hash",
    slug: "hash",
    yard: "text",
    tagline: "MD5, SHA-1, SHA-256 checksums",
    incumbent: "",
  },
  {
    name: "JWT Decoder",
    slug: "jwt",
    yard: "text",
    tagline: "Decode & inspect JWT tokens",
    incumbent: "jwt.io",
  },
  {
    name: "Lorem Ipsum",
    slug: "lorem",
    yard: "text",
    tagline: "Placeholder text and images",
    incumbent: "lipsum",
  },
  {
    name: "Transcribe",
    slug: "transcribe",
    yard: "ai",
    tagline: "Whisper speech to text",
    incumbent: "Otter.ai",
  },
  {
    name: "Upscale",
    slug: "upscale",
    yard: "ai",
    tagline: "AI super-resolution 2x and 4x",
    incumbent: "Upscayl",
  },
  {
    name: "Depth Map",
    slug: "depth",
    yard: "ai",
    tagline: "Turn a photo into a depth map",
    incumbent: "Depth-Anything",
  },
  {
    name: "Caption",
    slug: "caption",
    yard: "ai",
    tagline: "Describe any image for alt text",
    incumbent: "BLIP",
  },
  {
    name: "Translate",
    slug: "translate",
    yard: "ai",
    tagline: "200 languages, on your device",
    incumbent: "DeepL",
  },
  {
    name: "Summarize",
    slug: "summarize",
    yard: "ai",
    tagline: "Summarize long text and articles",
    incumbent: "QuillBot",
  },
  {
    name: "Local Chat",
    slug: "chat",
    yard: "ai",
    tagline: "An LLM running in your browser",
    incumbent: "ChatGPT",
  },
  {
    name: "PDF Toolkit",
    slug: "pdf",
    yard: "docs",
    tagline: "Merge, split & compress PDFs",
    incumbent: "iLovePDF",
  },
  {
    name: "Subtitle Editor",
    slug: "subs",
    yard: "docs",
    tagline: "Edit, shift & convert .srt/.vtt",
    incumbent: "Subtitle Edit",
  },
  {
    name: "Password",
    slug: "password",
    yard: "docs",
    tagline: "Strong, random passwords",
    incumbent: "1Password",
  },
  {
    name: "Unit Converter",
    slug: "units",
    yard: "docs",
    tagline: "Length, weight, temperature & more",
    incumbent: "Google",
  },
  {
    name: "Colours",
    slug: "colours",
    yard: "docs",
    tagline: "Gradients, palettes & contrast",
    incumbent: "Coolors",
  },
  {
    name: "Cron Builder",
    slug: "cron",
    yard: "docs",
    tagline: "Build & decode cron schedules",
    incumbent: "crontab.guru",
  },
  {
    name: "Barcode",
    slug: "barcode",
    yard: "docs",
    tagline: "Code128, EAN, UPC barcodes",
    incumbent: "TEC-IT",
  },
  {
    name: "Invoice",
    slug: "invoice",
    yard: "docs",
    tagline: "Fill & export an invoice PDF",
    incumbent: "invoice-generator",
  },
  {
    name: "Resume",
    slug: "resume",
    yard: "docs",
    tagline: "Build a CV, export to PDF",
    incumbent: "Zety",
  },
  {
    name: "E-Signature",
    slug: "sign",
    yard: "docs",
    tagline: "Sign a PDF in your browser",
    incumbent: "DocuSign",
  },
];
