export type Yard = "image" | "text" | "ai" | "docs";

export interface Tool {
  name: string;
  slug: string;
  yard: Yard;
  tagline: string;
  /** The paid incumbent this tool replaces. Empty string = show "free forever". */
  incumbent: string;
}

export const YARDS: { id: Yard; label: string }[] = [
  { id: "image", label: "Image & Media" },
  { id: "text", label: "Text & Code" },
  { id: "ai", label: "In-browser AI" },
  { id: "docs", label: "Docs & Utility" },
];

// Order is canonical; card numbers (#NN) are derived from index + 1.
// Source of truth lives in apps/*/junkyard.json; generated by scripts/gen-catalogue.mjs.
export { TOOLS } from "./catalogue.generated";
