#!/usr/bin/env node
// Reads apps/*/junkyard.ts, validates, sorts by order, and emits:
//   hub/src/catalogue.generated.ts  - typed TOOLS array for the hub
//   hub/public/catalogue.json       - full catalogue for nav switcher and MCP server
// Run via: npx tsx scripts/gen-catalogue.ts

import { writeFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { JunkyardApp } from "./catalogue-schema.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const APPS_DIR = join(ROOT, "apps");
const OUT_TS = join(ROOT, "hub", "src", "catalogue.generated.ts");
const OUT_JSON = join(ROOT, "hub", "public", "catalogue.json");

const VALID_CATEGORIES = new Set<string>(["image", "text", "ai", "docs"]);
const VALID_RUNTIMES = new Set<string>(["client", "client-ai"]);

const REQUIRED_FIELDS: (keyof JunkyardApp)[] = [
  "slug",
  "name",
  "category",
  "order",
  "tagline",
  "description",
  "incumbent",
  "path",
  "runtime",
  "mcp",
];

async function main(): Promise<void> {
  // Collect all app directory names
  const appDirs = readdirSync(APPS_DIR).filter((name) => {
    try {
      return statSync(join(APPS_DIR, name)).isDirectory();
    } catch {
      return false;
    }
  });

  const tools: JunkyardApp[] = [];
  const errors: string[] = [];

  for (const dir of appDirs) {
    const tsPath = join(APPS_DIR, dir, "junkyard.ts");
    let mod: { app: JunkyardApp };

    try {
      mod = await import(pathToFileURL(tsPath).href);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      errors.push(`Failed to import ${tsPath}: ${msg}`);
      continue;
    }

    const data = mod.app;

    if (!data || typeof data !== "object") {
      errors.push(`${tsPath}: export "app" is missing or not an object`);
      continue;
    }

    // Required fields
    for (const field of REQUIRED_FIELDS) {
      if (data[field] === undefined || data[field] === null) {
        errors.push(`${tsPath}: missing required field "${field}"`);
      }
    }

    if (errors.length > 0) continue;

    // Category validation
    if (!VALID_CATEGORIES.has(data.category)) {
      errors.push(
        `${tsPath}: category "${data.category}" not in [image, text, ai, docs]`,
      );
    }

    // Runtime validation
    if (!VALID_RUNTIMES.has(data.runtime)) {
      errors.push(
        `${tsPath}: runtime "${data.runtime}" not in [client, client-ai]`,
      );
    }

    // Slug must match directory name
    if (data.slug !== dir) {
      errors.push(
        `${tsPath}: slug "${data.slug}" does not match directory name "${dir}"`,
      );
    }

    // Order must be a positive integer
    if (!Number.isInteger(data.order) || data.order < 1) {
      errors.push(
        `${tsPath}: order must be a positive integer, got ${JSON.stringify(data.order)}`,
      );
    }

    if (errors.length === 0) {
      tools.push(data);
    }
  }

  if (errors.length > 0) {
    for (const err of errors) {
      process.stderr.write(`ERROR: ${err}\n`);
    }
    process.exit(1);
  }

  // Def count must equal app-dir count
  if (tools.length !== appDirs.length) {
    process.stderr.write(
      `ERROR: found ${tools.length} valid junkyard.ts files but ${appDirs.length} app directories - a definition is missing or invalid\n`,
    );
    process.exit(1);
  }

  // Order values must be unique
  const orderSet = new Set(tools.map((t) => t.order));
  if (orderSet.size !== tools.length) {
    const seen = new Set<number>();
    const dupes: string[] = [];
    for (const t of tools) {
      if (seen.has(t.order)) dupes.push(`order ${t.order} (slug: ${t.slug})`);
      seen.add(t.order);
    }
    process.stderr.write(`ERROR: duplicate order values: ${dupes.join(", ")}\n`);
    process.exit(1);
  }

  // Order set must be exactly 1..N
  const N = tools.length;
  for (let i = 1; i <= N; i++) {
    if (!orderSet.has(i)) {
      process.stderr.write(
        `ERROR: order values must be exactly 1..${N}, but ${i} is missing\n`,
      );
      process.exit(1);
    }
  }

  // Sort by order ascending
  tools.sort((a, b) => a.order - b.order);

  // Emit catalogue.generated.ts (only Tool fields: name, slug, yard=category, tagline, incumbent)
  const tsLines = [
    `// AUTO-GENERATED by scripts/gen-catalogue.ts from apps/*/junkyard.ts. DO NOT EDIT.`,
    `import type { Tool } from "./tools";`,
    ``,
    `export const TOOLS: Tool[] = [`,
  ];

  for (const t of tools) {
    tsLines.push(`  {`);
    tsLines.push(`    name: ${JSON.stringify(t.name)},`);
    tsLines.push(`    slug: ${JSON.stringify(t.slug)},`);
    tsLines.push(`    yard: ${JSON.stringify(t.category)},`);
    tsLines.push(`    tagline: ${JSON.stringify(t.tagline)},`);
    tsLines.push(`    incumbent: ${JSON.stringify(t.incumbent)},`);
    tsLines.push(`  },`);
  }

  tsLines.push(`];`);
  tsLines.push(``);

  writeFileSync(OUT_TS, tsLines.join("\n"), "utf-8");

  // Emit catalogue.json (full catalogue, all fields, plain JSON array)
  writeFileSync(OUT_JSON, JSON.stringify(tools, null, 2) + "\n", "utf-8");

  process.stdout.write(`generated ${tools.length} tools\n`);
}

main();
