#!/usr/bin/env node
// Reads apps/*/junkyard.ts, validates with zod, sorts by order, and emits:
//   hub/src/catalogue.generated.ts  - typed TOOLS array for the hub
//   hub/public/catalogue.json       - full catalogue for nav switcher and MCP server
// Run via: npx tsx scripts/gen-catalogue.ts

import { writeFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { JunkyardAppSchema, type JunkyardApp } from "./catalogue-schema.ts";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const APPS_DIR = join(ROOT, "apps");
const OUT_TS = join(ROOT, "hub", "src", "catalogue.generated.ts");
const OUT_JSON = join(ROOT, "hub", "public", "catalogue.json");

const DESC_TERMINAL_RE = /[.!?]$/;

function validateDescription(desc: string, slug: string): string[] {
  const errs: string[] = [];
  if (desc.length < 40) {
    errs.push(`[${slug}] description too short (${desc.length} chars, min 40) - "${desc}"`);
  } else if (!DESC_TERMINAL_RE.test(desc)) {
    errs.push(`[${slug}] description does not end with sentence-ending punctuation (.!?) - "${desc}"`);
  }
  return errs;
}

async function main(): Promise<void> {
  // Collect all app directory names
  const appDirs = readdirSync(APPS_DIR).filter((name) => {
    try {
      return statSync(join(APPS_DIR, name)).isDirectory();
    } catch {
      return false;
    }
  });

  const tools: JunkyardApp[] = [];
  // All errors across all apps accumulated before exit so every problem is reported
  const allErrors: string[] = [];

  for (const dir of appDirs) {
    const tsPath = join(APPS_DIR, dir, "junkyard.ts");
    let mod: { app: Record<string, unknown> };

    try {
      mod = await import(pathToFileURL(tsPath).href);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      allErrors.push(`Failed to import ${tsPath}: ${msg}`);
      continue;
    }

    const data = mod.app;

    if (!data || typeof data !== "object") {
      allErrors.push(`${tsPath}: export "app" is missing or not an object`);
      continue;
    }

    // Zod schema validation — reports all field errors at once
    const result = JunkyardAppSchema.safeParse(data);
    if (!result.success) {
      for (const issue of result.error.issues) {
        const pathStr = issue.path.join(".");
        allErrors.push(`[${dir}] ${pathStr}: ${issue.message}`);
      }
      continue;
    }

    const app = result.data;

    // Slug must match directory name (zod doesn't have access to the dir name)
    if (app.slug !== dir) {
      allErrors.push(`[${dir}] slug "${app.slug}" does not match directory name "${dir}"`);
      continue;
    }

    // Path must be the canonical derivative of slug: "/<slug>/"
    const expectedPath = `/${app.slug}/`;
    if (app.path !== expectedPath) {
      allErrors.push(`[${dir}] path "${app.path}" must be "${expectedPath}"`);
      continue;
    }

    // Description quality: min length (zod checks >= 40) and terminal punctuation
    allErrors.push(...validateDescription(app.description, dir));

    if (allErrors.length > 0 && allErrors.some((e) => e.startsWith(`[${dir}]`))) {
      // Don't push partial data — skip this app entirely
      continue;
    }

    tools.push(app);
  }

  if (allErrors.length > 0) {
    for (const err of allErrors) {
      process.stderr.write(`ERROR: ${err}\n`);
    }
    process.exit(1);
  }

  // Def count must equal app-dir count
  if (tools.length !== appDirs.length) {
    process.stderr.write(
      `ERROR: found ${tools.length} valid junkyard.ts files but ${appDirs.length} app directories - a definition is missing or invalid\n`,
    );
    process.exit(1);
  }

  // Order values must be unique
  const orderSet = new Set(tools.map((t) => t.order));
  if (orderSet.size !== tools.length) {
    const seen = new Set<number>();
    const dupes: string[] = [];
    for (const t of tools) {
      if (seen.has(t.order)) dupes.push(`order ${t.order} (slug: ${t.slug})`);
      seen.add(t.order);
    }
    process.stderr.write(`ERROR: duplicate order values: ${dupes.join(", ")}\n`);
    process.exit(1);
  }

  // Order set must be exactly 1..N
  const N = tools.length;
  for (let i = 1; i <= N; i++) {
    if (!orderSet.has(i)) {
      process.stderr.write(
        `ERROR: order values must be exactly 1..${N}, but ${i} is missing\n`,
      );
      process.exit(1);
    }
  }

  // Sort by order ascending
  tools.sort((a, b) => a.order - b.order);

  // Emit catalogue.generated.ts (Tool fields: name, slug, yard=category, tagline, incumbent, tags, mcpExposed)
  const tsLines = [
    `// AUTO-GENERATED by scripts/gen-catalogue.ts from apps/*/junkyard.ts. DO NOT EDIT.`,
    `import type { Tool } from "./tools";`,
    ``,
    `export const TOOLS: Tool[] = [`,
  ];

  for (const t of tools) {
    tsLines.push(`  {`);
    tsLines.push(`    name: ${JSON.stringify(t.name)},`);
    tsLines.push(`    slug: ${JSON.stringify(t.slug)},`);
    tsLines.push(`    yard: ${JSON.stringify(t.category)},`);
    tsLines.push(`    tagline: ${JSON.stringify(t.tagline)},`);
    tsLines.push(`    incumbent: ${JSON.stringify(t.incumbent)},`);
    if (t.tags && t.tags.length > 0) {
      const tagList = t.tags.map((tag) => JSON.stringify(tag)).join(", ");
      tsLines.push(`    tags: [${tagList}],`);
    }
    tsLines.push(`    mcpExposed: ${t.mcp.exposed},`);
    tsLines.push(`  },`);
  }

  tsLines.push(`];`);
  tsLines.push(``);

  writeFileSync(OUT_TS, tsLines.join("\n"), "utf-8");

  // Emit catalogue.json (full catalogue, all fields, plain JSON array)
  writeFileSync(OUT_JSON, JSON.stringify(tools, null, 2) + "\n", "utf-8");

  process.stdout.write(`generated ${tools.length} tools\n`);
}

main();
